[package]
name = "bevy-marching-cubes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.15.2"
bevy = "0.5"
bevy_flycam = "0.5.1"